version: '3.1'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd:/fluentd/etc
    environment:
      - FLUENTD_CONF=fluentd.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
  node:
    image: node:latest
    working_dir: /app
    volumes:
      - ./app:/app
    command: ["npm", "run", "start"]
    ports:
      - "3000:3000"
    depends_on:
      - fluentd
